### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by omarwright07** [omarwright07/bill-splitter#1]
### Mvp: 
split bill by number of people and tip percentage 

### Extra:

- [ ] Can stack multiple bills together and display
- [ ] Saves previous bill splits
- [ ] Save friends names and history
- [ ] Set percentages bases on members to pay
- [ ] Be able to substract set dollar amounts 
- [ ] Show the remainder/extra for someone of the group to pay, in case of uneven split 
- [ ] Select who pays any thing extra/remainder 
- [ ] Categories the bills e.i. Rent, electric, water etc
- [ ] Name the bill for save history 
- [ ] Tracker to see who paid their share already 
- [ ] Shareable to other people
